### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by disRecord**
Since Jan 1 2020 python2 should be considered deprecated. This pull request updates Scons build system to 3.1.2 version to introduce python3 support. It also works with python2 then it should not break old installations. 

Possible issues:
1. I have not tested tcl support.
2. RPATH behavior. Old version sets RPATH automatically, but now additional configuration variable is required. Now it is set to installation path.

### CODE REVIEW

**Comment by JBoggsy** [comment]
Can we please do this? It's about time we updated SCons, and this says it won't break with old code.

**Comment by marinier** [comment]
I also vote for this -- I actually have a project that this would help. That said, the Tcl does need to work, as well as the generated Python 3 SML interface.

**Comment by mazina** [comment]
Hey guys, there’s no need for convincing.  This was definitely something
that was already high on the priority list for future releases. I would
just need to check out what was changed and test it.  Boggs, I might ask
you to check it out on the windows side since we don’t have our Jenkins
test machines any more.

Thanks for contribution, disRecord!  I’ll let you know if I have any
questions on what you submitted.

**Comment by JBoggsy** [comment]
@mazina Will do. Also will look into setting up Jenkins. I'd love to get Soar a bit more, well, production-quality.

**Comment by disRecord** [comment]
I noticed an error in platform identification code (sys.platform has different values in python2 and python3). Now TCL is working (at least in linux) and RPATH issue should also be fixed.

For better commit history I can rewrite git history if it necessary.

**Comment by mazina** [comment]
FYI, I pulled your pr into a branch and tried it out.  It worked on linux but had issues on OSX and Windows.  I also found a couple other new problems that needed to be fixed, which were not related to python 3.   I think I have found solutions for everything, and it's now working on the 3 platforms again, at least for me.  It definitely needs to be tested on more machines/configurations.  Hopefully, people can help out on that.

The updates are merged into development.  Please me know if you have any problems building.  Bob, you may need to update to the latest version of ActiveTcl on Windows to get the tcl interface to build.

**Comment by marinier** [comment]
We have tested it on Windows and Linux and it's working for us!

**Pull request closed without merging**
