### PR TITLE
allow compiling out SVS (2)

### PR DESCRIPTION
**Pull request by garfieldnate**
An error last time meant that --no-svs would break building 
Swig wrappers. This PR provides a --no-svs option and 
properly builds with Swig as well (so `build all` works). 
Uses the `-D` switch provided for defining macros with Swig.

### CODE REVIEW

**Comment by garfieldnate** [comment]
I can do more work on this if it's needed. Did it not work for you?

**Comment by mazina** [comment]
It did work.  I just merged it via a branch, using that hub extension, so I
could test it a bit first.

**Comment by garfieldnate** [comment]
Oh, good. I think once you push the merge it closes automatically.

**Comment by garfieldnate** [comment]
Merged as d3a3c1b2 and 8e43123.

**Pull request closed without merging**
