### PR TITLE
Colors and Emoji on Windows

### PR DESCRIPTION
**Pull request by garfieldnate**
Windows Terminal and PowerShell both support emoji and colors, so there's no need to be precious about avoiding them on Windows anymore. We do need to make sure to use the more portable `\033`, as `\e` is only recognized by some languages/environments, and is not recognized in MSVC.

### CODE REVIEW

**Comment by garfieldnate** [comment]
@marinier could you build this locally and check that the plain Soar CLI uses colors now?

**Comment by marinier** [comment]
It looks like the output on windows is messed up now. Here's a screenshot:

image

**Comment by marinier** [comment]
So, the above screenshot came from just double-clicking `soar.exe`, which I think opened in the default command prompt (cmd). I launched it from windows terminal instead and it worked!

image

The issue here is that most people are probably going to just double-click on it. I wonder if there is a way to detect whether colors are supported at runtime and to dynamically change what it does so it works (without colors) if run in a terminal that doesn't support colors, or with colors if the terminal supports colors.

**Comment by marinier** [comment]
Another possible solution would be to generate two .exes, one with color support and one without, and allow the user to run whichever one they want.

**Comment by garfieldnate** [comment]
@marinier Should be fixed now. I tested on one Windows machine, but if you could double-check that would be fantastic. It now checks directly if stdout supports ANSI escapes.

**Comment by marinier** [comment]
It's working! When I double-click I get the no-color version, and when I run from windows terminal I get the colored version.

My only question is about the emoji (from the title of this PR). I haven't seen any emoji in the testing I've done (which is mostly just to run cli). What do I need to do to confirm that emoji are working?

**Comment by garfieldnate** [comment]
Emoji are only printed from the unit tests (the green checkmark). I removed the check there completely, with the assumption that developers won't limit themselves to CMD.

**Comment by marinier** [comment]
The unit tests do not appear to be working with colored output / emojis. Here's what the output looks like running in windows terminal:

image

**Comment by garfieldnate** [comment]
Oookay, I checked the unit tests with Windows Terminal and I'm getting ✅  nicely printed. Unless you think anything else is missing, I'll merge this in the next couple of days. Thanks for your help!

**Comment by marinier** [comment]
Confirmed it looks great!

**Pull request merged**
